"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 21:53:16.514325
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_number', sa.String(length=32), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('applicant_type', sa.Enum('SOLE_PROPRIETOR', 'PARTNERSHIP', 'LLP', 'PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'OTHER', name='applicanttype', native_enum=False, length=40), nullable=False),
    sa.Column('loan_type', sa.Enum('TERM_LOAN', 'WORKING_CAPITAL', 'PERSONAL_BUSINESS_LOAN', 'MACHINERY_LOAN', 'OTHER', name='loantype', native_enum=False, length=40), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('loan_purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'DOCUMENTS_RECEIVED', 'PROCESSING', 'NEEDS_REVIEW', 'PROCESSED', name='applicationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('document_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_application_number'), 'applications', ['application_number'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_application_id'), 'audit_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('detected_mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('document_type', sa.Enum('PAN', 'KYC', 'GST_CERTIFICATE', 'GST_RETURN', 'UDYAM', 'BANK_STATEMENT', 'ITR', 'PROFIT_LOSS', 'BALANCE_SHEET', 'CASH_FLOW', 'LOAN_STATEMENT', 'BUSINESS_REGISTRATION', 'PARTNERSHIP_DEED', 'LLP_AGREEMENT', 'MOA', 'AOA', 'QUOTATION', 'BUSINESS_PLAN', 'UNKNOWN', name='documenttype', native_enum=False, length=40), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_method', sa.Enum('filename', 'rule', 'layout', 'llm', 'manual', 'none', name='classificationmethod', native_enum=False, length=40), nullable=True),
    sa.Column('classification_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('type_overridden', sa.Boolean(), nullable=False),
    sa.Column('document_status', sa.Enum('UPLOADED', 'VALIDATING', 'VALID', 'INVALID', 'PROCESSING', 'PROCESSED', 'NEEDS_REVIEW', 'FAILED', name='documentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('file_validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('processing_run', sa.Integer(), nullable=False),
    sa.Column('raw_extraction_key', sa.String(length=1024), nullable=True),
    sa.Column('status_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_application_id'), 'documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('check_code', sa.String(length=64), nullable=False),
    sa.Column('check_group', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'INCONSISTENCY', 'NEEDS_REVIEW', 'INSUFFICIENT_DATA', 'SKIPPED', name='checkstatus', native_enum=False, length=40), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_application_id'), 'reconciliation_results', ['application_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_check_code'), 'reconciliation_results', ['check_code'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('text_source', sa.Enum('TEXT_LAYER', 'OCR', 'SPREADSHEET', 'NONE', name='textsource', native_enum=False, length=40), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('image_quality', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_page_per_document')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('extracted_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('table_type', sa.Enum('TRANSACTIONS', 'FINANCIAL_STATEMENT', 'GENERIC', name='tabletype', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('header', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('column_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_rows', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('rows_needs_review', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_tables_document_id'), 'extracted_tables', ['document_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.Enum('UPLOAD_VALIDATION', 'DOCUMENT_PROCESSING', 'APPLICATION_RECONCILIATION', name='jobtype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='jobstatus', native_enum=False, length=40), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_application_id'), 'processing_jobs', ['application_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_missing', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_location', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('source_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_row_index', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.Enum('REGEX', 'LABEL', 'TABLE', 'LAYOUT', 'DERIVED', 'LLM', 'MANUAL', 'NONE', name='extractionmethod', native_enum=False, length=40), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALID', 'INVALID', 'NEEDS_REVIEW', 'MISSING', name='fieldvalidationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('alternatives', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('processing_run', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['extracted_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_application_id'), 'extracted_fields', ['application_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_field_name'), 'extracted_fields', ['field_name'], unique=False)
    op.create_table('extracted_table_rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('row_kind', sa.Enum('TRANSACTION', 'OPENING_BALANCE', 'CLOSING_BALANCE', 'SUMMARY', 'HEADER', 'CONTINUATION', 'LINE_ITEM', 'UNPARSED', name='rowkind', native_enum=False, length=40), nullable=False),
    sa.Column('raw_cells', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('parsed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('EXTRACTED', 'VALIDATED', 'NEEDS_REVIEW', 'FAILED', name='rowstatus', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['extracted_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_table_rows_document_id'), 'extracted_table_rows', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_table_rows_table_id'), 'extracted_table_rows', ['table_id'], unique=False)
    op.create_table('processing_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('FILE_VALIDATION', 'CLASSIFICATION', 'TEXT_EXTRACTION', 'TABLE_EXTRACTION', 'FIELD_EXTRACTION', 'FIELD_VALIDATION', 'DOCUMENT_VALIDATION', 'CROSS_DOCUMENT_RECONCILIATION', 'COMPLETENESS_CHECK', 'FINAL_DOCUMENT_STATUS', name='processingstage', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', 'SKIPPED', name='stagestatus', native_enum=False, length=40), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('warnings_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_stages_document_id'), 'processing_stages', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_stages_job_id'), 'processing_stages', ['job_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=True),
    sa.Column('row_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.Enum('FILE', 'FIELD', 'ROW', 'DOCUMENT', name='validationscope', native_enum=False, length=40), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'INCONSISTENCY', 'NEEDS_REVIEW', 'INSUFFICIENT_DATA', 'SKIPPED', name='checkstatus', native_enum=False, length=40), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['extracted_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['extracted_table_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_application_id'), 'validation_results', ['application_id'], unique=False)
    op.create_index(op.f('ix_validation_results_document_id'), 'validation_results', ['document_id'], unique=False)
    op.create_index(op.f('ix_validation_results_field_id'), 'validation_results', ['field_id'], unique=False)
    op.create_index(op.f('ix_validation_results_row_id'), 'validation_results', ['row_id'], unique=False)
    op.create_index(op.f('ix_validation_results_rule_code'), 'validation_results', ['rule_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_rule_code'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_row_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_field_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_document_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_application_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_processing_stages_job_id'), table_name='processing_stages')
    op.drop_index(op.f('ix_processing_stages_document_id'), table_name='processing_stages')
    op.drop_table('processing_stages')
    op.drop_index(op.f('ix_extracted_table_rows_table_id'), table_name='extracted_table_rows')
    op.drop_index(op.f('ix_extracted_table_rows_document_id'), table_name='extracted_table_rows')
    op.drop_table('extracted_table_rows')
    op.drop_index(op.f('ix_extracted_fields_field_name'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_application_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_application_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_extracted_tables_document_id'), table_name='extracted_tables')
    op.drop_table('extracted_tables')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_reconciliation_results_check_code'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_application_id'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_application_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_application_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_application_number'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
